#############################################################################
# Makefile for building: PointViewer
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  ExerciseCOG.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ExerciseCOG.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PointViewer1.0.0
DISTDIR = /home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry/.tmp/PointViewer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		CgEvents/CgLoadHalfEdgeMeshEvent.cpp \
		CgEvents/CgLoadMeshEvent.cpp \
		CgEvents/CgLoadPointCloudEvent.cpp \
		CgEvents/CgPickRayEvent.cpp \
		CgEvents/CgSplatEvent.cpp \
		CgMath/CgEigenDecomposition3x3.cpp \
		CgQtViewer/CGQtGLRenderWidget.cpp \
		CgQtViewer/CgQtGui.cpp \
		CgBase/CgObservable.cpp \
		CgEvents/CgMouseEvent.cpp \
		CgQtViewer/CgQtMainApplication.cpp \
		CgSceneGraph/CgHalfEdgePrimitives.cpp \
		CgSceneGraph/CgHalfEdgeTriangleMesh.cpp \
		CgSceneGraph/CgPointCloud.cpp \
		CgSceneGraph/CgPolyLine.cpp \
		CgSceneGraph/CgSceneControl.cpp \
		CgEvents/CgKeyEvent.cpp \
		CgEvents/CgButtonClickEvent.cpp \
		CgQtViewer/CgQtGlBufferObject.cpp \
		CgQtViewer/CgTrackball.cpp \
		CgEvents/CgWindowResizeEvent.cpp \
		CgSceneGraph/CgTriangleMesh.cpp \
		CgUtils/ObjLoader.cpp \
		CgEvents/CgTrackballEvent.cpp moc_CgQtGLRenderWidget.cpp \
		moc_CgQtGui.cpp \
		moc_CgQtMainApplication.cpp
OBJECTS       = main.o \
		CgLoadHalfEdgeMeshEvent.o \
		CgLoadMeshEvent.o \
		CgLoadPointCloudEvent.o \
		CgPickRayEvent.o \
		CgSplatEvent.o \
		CgEigenDecomposition3x3.o \
		CGQtGLRenderWidget.o \
		CgQtGui.o \
		CgObservable.o \
		CgMouseEvent.o \
		CgQtMainApplication.o \
		CgHalfEdgePrimitives.o \
		CgHalfEdgeTriangleMesh.o \
		CgPointCloud.o \
		CgPolyLine.o \
		CgSceneControl.o \
		CgKeyEvent.o \
		CgButtonClickEvent.o \
		CgQtGlBufferObject.o \
		CgTrackball.o \
		CgWindowResizeEvent.o \
		CgTriangleMesh.o \
		ObjLoader.o \
		CgTrackballEvent.o \
		moc_CgQtGLRenderWidget.o \
		moc_CgQtGui.o \
		moc_CgQtMainApplication.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ExerciseCOG.pro CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgEvents/CgLoadHalfEdgeMeshEvent.h \
		CgEvents/CgLoadMeshEvent.h \
		CgEvents/CgLoadPointCloudEvent.h \
		CgEvents/CgPickRayEvent.h \
		CgEvents/CgSplatEvent.h \
		CgMath/CgEigenDecomposition3x3.h \
		CgMath/Eigen/Core \
		CgMath/Eigen/Eigen \
		CgMath/Eigen/SVD \
		CgQtViewer/CgQtGLRenderWidget.h \
		CgQtViewer/CgQtGui.h \
		CgBase/CgObserver.h \
		CgBase/CgObservable.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h \
		CgEvents/CgMouseEvent.h \
		CgQtViewer/CgQtMainApplication.h \
		CgSceneGraph/CgHalfEdgePrimitives.h \
		CgSceneGraph/CgHalfEdgeTriangleMesh.h \
		CgSceneGraph/CgPointCloud.h \
		CgSceneGraph/CgPolyLine.h \
		CgSceneGraph/CgSceneControl.h \
		CgEvents/CgKeyEvent.h \
		CgEvents/CgButtonClickEvent.h \
		CgBase/CgBaseRenderer.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgBasePointCloud.h \
		CgBase/CgBaseTriangleMesh.h \
		CgBase/CgBasePolyline.h \
		CgBase/CgBaseSceneControl.h \
		CgQtViewer/CgQtGlBufferObject.h \
		CgQtViewer/CgTrackball.h \
		CgEvents/CgWindowResizeEvent.h \
		CgSceneGraph/CgTriangleMesh.h \
		CgUtils/ObjLoader.h \
		CgBase/CgBaseImage.h \
		CgEvents/CgTrackballEvent.h main.cpp \
		CgEvents/CgLoadHalfEdgeMeshEvent.cpp \
		CgEvents/CgLoadMeshEvent.cpp \
		CgEvents/CgLoadPointCloudEvent.cpp \
		CgEvents/CgPickRayEvent.cpp \
		CgEvents/CgSplatEvent.cpp \
		CgMath/CgEigenDecomposition3x3.cpp \
		CgQtViewer/CGQtGLRenderWidget.cpp \
		CgQtViewer/CgQtGui.cpp \
		CgBase/CgObservable.cpp \
		CgEvents/CgMouseEvent.cpp \
		CgQtViewer/CgQtMainApplication.cpp \
		CgSceneGraph/CgHalfEdgePrimitives.cpp \
		CgSceneGraph/CgHalfEdgeTriangleMesh.cpp \
		CgSceneGraph/CgPointCloud.cpp \
		CgSceneGraph/CgPolyLine.cpp \
		CgSceneGraph/CgSceneControl.cpp \
		CgEvents/CgKeyEvent.cpp \
		CgEvents/CgButtonClickEvent.cpp \
		CgQtViewer/CgQtGlBufferObject.cpp \
		CgQtViewer/CgTrackball.cpp \
		CgEvents/CgWindowResizeEvent.cpp \
		CgSceneGraph/CgTriangleMesh.cpp \
		CgUtils/ObjLoader.cpp \
		CgEvents/CgTrackballEvent.cpp
QMAKE_TARGET  = PointViewer
DESTDIR       = 
TARGET        = PointViewer


first: all
####### Build rules

PointViewer:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ExerciseCOG.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ExerciseCOG.pro
	$(QMAKE) -o Makefile ExerciseCOG.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ExerciseCOG.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ExerciseCOG.pro

qmake_all: FORCE


all: Makefile PointViewer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CgBase/CgBaseHalfEdgeTriangleMesh.h CgBase/CgBaseHalfdgePrimitives.h CgEvents/CgLoadHalfEdgeMeshEvent.h CgEvents/CgLoadMeshEvent.h CgEvents/CgLoadPointCloudEvent.h CgEvents/CgPickRayEvent.h CgEvents/CgSplatEvent.h CgMath/CgEigenDecomposition3x3.h CgMath/Eigen/Core CgMath/Eigen/Eigen CgMath/Eigen/SVD CgQtViewer/CgQtGLRenderWidget.h CgQtViewer/CgQtGui.h CgBase/CgObserver.h CgBase/CgObservable.h CgBase/CgBaseEvent.h CgBase/CgEnums.h CgEvents/CgMouseEvent.h CgQtViewer/CgQtMainApplication.h CgSceneGraph/CgHalfEdgePrimitives.h CgSceneGraph/CgHalfEdgeTriangleMesh.h CgSceneGraph/CgPointCloud.h CgSceneGraph/CgPolyLine.h CgSceneGraph/CgSceneControl.h CgEvents/CgKeyEvent.h CgEvents/CgButtonClickEvent.h CgBase/CgBaseRenderer.h CgBase/CgBaseRenderableObject.h CgBase/CgBasePointCloud.h CgBase/CgBaseTriangleMesh.h CgBase/CgBasePolyline.h CgBase/CgBaseSceneControl.h CgQtViewer/CgQtGlBufferObject.h CgQtViewer/CgTrackball.h CgEvents/CgWindowResizeEvent.h CgSceneGraph/CgTriangleMesh.h CgUtils/ObjLoader.h CgBase/CgBaseImage.h CgEvents/CgTrackballEvent.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp CgEvents/CgLoadHalfEdgeMeshEvent.cpp CgEvents/CgLoadMeshEvent.cpp CgEvents/CgLoadPointCloudEvent.cpp CgEvents/CgPickRayEvent.cpp CgEvents/CgSplatEvent.cpp CgMath/CgEigenDecomposition3x3.cpp CgQtViewer/CGQtGLRenderWidget.cpp CgQtViewer/CgQtGui.cpp CgBase/CgObservable.cpp CgEvents/CgMouseEvent.cpp CgQtViewer/CgQtMainApplication.cpp CgSceneGraph/CgHalfEdgePrimitives.cpp CgSceneGraph/CgHalfEdgeTriangleMesh.cpp CgSceneGraph/CgPointCloud.cpp CgSceneGraph/CgPolyLine.cpp CgSceneGraph/CgSceneControl.cpp CgEvents/CgKeyEvent.cpp CgEvents/CgButtonClickEvent.cpp CgQtViewer/CgQtGlBufferObject.cpp CgQtViewer/CgTrackball.cpp CgEvents/CgWindowResizeEvent.cpp CgSceneGraph/CgTriangleMesh.cpp CgUtils/ObjLoader.cpp CgEvents/CgTrackballEvent.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CgQtGLRenderWidget.cpp moc_CgQtGui.cpp moc_CgQtMainApplication.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CgQtGLRenderWidget.cpp moc_CgQtGui.cpp moc_CgQtMainApplication.cpp
moc_CgQtGLRenderWidget.cpp: CgQtViewer/CgQtGLRenderWidget.h \
		CgBase/CgBaseRenderer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CgQtViewer/CgQtGLRenderWidget.h -o moc_CgQtGLRenderWidget.cpp

moc_CgQtGui.cpp: CgQtViewer/CgQtGui.h \
		CgBase/CgObservable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CgQtViewer/CgQtGui.h -o moc_CgQtGui.cpp

moc_CgQtMainApplication.cpp: CgQtViewer/CgQtMainApplication.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/stud/pzh-tax-u1/Dokumente/COG/ComputationalGeometry -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CgQtViewer/CgQtMainApplication.h -o moc_CgQtMainApplication.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp CgQtViewer/CgQtMainApplication.h \
		CgQtViewer/CgQtGLRenderWidget.h \
		CgBase/CgBaseRenderer.h \
		CgQtViewer/CgQtGui.h \
		CgBase/CgObservable.h \
		CgSceneGraph/CgSceneControl.h \
		CgBase/CgObserver.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h \
		CgBase/CgBaseSceneControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

CgLoadHalfEdgeMeshEvent.o: CgEvents/CgLoadHalfEdgeMeshEvent.cpp CgEvents/CgLoadHalfEdgeMeshEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgLoadHalfEdgeMeshEvent.o CgEvents/CgLoadHalfEdgeMeshEvent.cpp

CgLoadMeshEvent.o: CgEvents/CgLoadMeshEvent.cpp CgEvents/CgLoadMeshEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgLoadMeshEvent.o CgEvents/CgLoadMeshEvent.cpp

CgLoadPointCloudEvent.o: CgEvents/CgLoadPointCloudEvent.cpp CgEvents/CgLoadPointCloudEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgLoadPointCloudEvent.o CgEvents/CgLoadPointCloudEvent.cpp

CgPickRayEvent.o: CgEvents/CgPickRayEvent.cpp CgEvents/CgPickRayEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgPickRayEvent.o CgEvents/CgPickRayEvent.cpp

CgSplatEvent.o: CgEvents/CgSplatEvent.cpp CgEvents/CgSplatEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgSplatEvent.o CgEvents/CgSplatEvent.cpp

CgEigenDecomposition3x3.o: CgMath/CgEigenDecomposition3x3.cpp CgMath/CgEigenDecomposition3x3.h \
		CgMath/Eigen/Dense \
		CgMath/Eigen/Core \
		CgMath/Eigen/src/Core/util/DisableStupidWarnings.h \
		CgMath/Eigen/src/Core/util/Macros.h \
		CgMath/Eigen/src/Core/util/MKL_support.h \
		CgMath/Eigen/src/misc/blas.h \
		CgMath/Eigen/src/Core/util/Constants.h \
		CgMath/Eigen/src/Core/util/Meta.h \
		CgMath/Eigen/src/Core/util/ForwardDeclarations.h \
		CgMath/Eigen/src/Core/util/StaticAssert.h \
		CgMath/Eigen/src/Core/util/XprHelper.h \
		CgMath/Eigen/src/Core/util/Memory.h \
		CgMath/Eigen/src/Core/NumTraits.h \
		CgMath/Eigen/src/Core/MathFunctions.h \
		CgMath/Eigen/src/Core/GenericPacketMath.h \
		CgMath/Eigen/src/Core/MathFunctionsImpl.h \
		CgMath/Eigen/src/Core/arch/Default/ConjHelper.h \
		CgMath/Eigen/src/Core/arch/SSE/PacketMath.h \
		CgMath/Eigen/src/Core/arch/SSE/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AVX/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AVX/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AVX512/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/SSE/Complex.h \
		CgMath/Eigen/src/Core/arch/AVX/Complex.h \
		CgMath/Eigen/src/Core/arch/AVX/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/SSE/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AltiVec/Complex.h \
		CgMath/Eigen/src/Core/arch/NEON/PacketMath.h \
		CgMath/Eigen/src/Core/arch/NEON/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/NEON/Complex.h \
		CgMath/Eigen/src/Core/arch/ZVector/PacketMath.h \
		CgMath/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/ZVector/Complex.h \
		CgMath/Eigen/src/Core/arch/CUDA/Half.h \
		CgMath/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		CgMath/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/CUDA/PacketMath.h \
		CgMath/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/Default/Settings.h \
		CgMath/Eigen/src/Core/functors/TernaryFunctors.h \
		CgMath/Eigen/src/Core/functors/BinaryFunctors.h \
		CgMath/Eigen/src/Core/functors/UnaryFunctors.h \
		CgMath/Eigen/src/Core/functors/NullaryFunctors.h \
		CgMath/Eigen/src/Core/functors/StlFunctors.h \
		CgMath/Eigen/src/Core/functors/AssignmentFunctors.h \
		CgMath/Eigen/src/Core/arch/CUDA/Complex.h \
		CgMath/Eigen/src/Core/IO.h \
		CgMath/Eigen/src/Core/DenseCoeffsBase.h \
		CgMath/Eigen/src/Core/DenseBase.h \
		CgMath/Eigen/src/plugins/BlockMethods.h \
		CgMath/Eigen/src/Core/MatrixBase.h \
		CgMath/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		CgMath/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		CgMath/Eigen/src/Core/EigenBase.h \
		CgMath/Eigen/src/Core/Product.h \
		CgMath/Eigen/src/Core/CoreEvaluators.h \
		CgMath/Eigen/src/Core/AssignEvaluator.h \
		CgMath/Eigen/src/Core/Assign.h \
		CgMath/Eigen/src/Core/ArrayBase.h \
		CgMath/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		CgMath/Eigen/src/Core/util/BlasUtil.h \
		CgMath/Eigen/src/Core/DenseStorage.h \
		CgMath/Eigen/src/Core/NestByValue.h \
		CgMath/Eigen/src/Core/ReturnByValue.h \
		CgMath/Eigen/src/Core/NoAlias.h \
		CgMath/Eigen/src/Core/PlainObjectBase.h \
		CgMath/Eigen/src/Core/Matrix.h \
		CgMath/Eigen/src/Core/Array.h \
		CgMath/Eigen/src/Core/CwiseTernaryOp.h \
		CgMath/Eigen/src/Core/CwiseBinaryOp.h \
		CgMath/Eigen/src/Core/CwiseUnaryOp.h \
		CgMath/Eigen/src/Core/CwiseNullaryOp.h \
		CgMath/Eigen/src/Core/CwiseUnaryView.h \
		CgMath/Eigen/src/Core/SelfCwiseBinaryOp.h \
		CgMath/Eigen/src/Core/Dot.h \
		CgMath/Eigen/src/Core/StableNorm.h \
		CgMath/Eigen/src/Core/Stride.h \
		CgMath/Eigen/src/Core/MapBase.h \
		CgMath/Eigen/src/Core/Map.h \
		CgMath/Eigen/src/Core/Ref.h \
		CgMath/Eigen/src/Core/Block.h \
		CgMath/Eigen/src/Core/VectorBlock.h \
		CgMath/Eigen/src/Core/Transpose.h \
		CgMath/Eigen/src/Core/DiagonalMatrix.h \
		CgMath/Eigen/src/Core/Diagonal.h \
		CgMath/Eigen/src/Core/DiagonalProduct.h \
		CgMath/Eigen/src/Core/Redux.h \
		CgMath/Eigen/src/Core/Visitor.h \
		CgMath/Eigen/src/Core/Fuzzy.h \
		CgMath/Eigen/src/Core/Swap.h \
		CgMath/Eigen/src/Core/CommaInitializer.h \
		CgMath/Eigen/src/Core/GeneralProduct.h \
		CgMath/Eigen/src/Core/Solve.h \
		CgMath/Eigen/src/Core/Inverse.h \
		CgMath/Eigen/src/Core/SolverBase.h \
		CgMath/Eigen/src/Core/PermutationMatrix.h \
		CgMath/Eigen/src/Core/Transpositions.h \
		CgMath/Eigen/src/Core/TriangularMatrix.h \
		CgMath/Eigen/src/Core/SelfAdjointView.h \
		CgMath/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		CgMath/Eigen/src/Core/products/Parallelizer.h \
		CgMath/Eigen/src/Core/ProductEvaluators.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixVector.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		CgMath/Eigen/src/Core/SolveTriangular.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		CgMath/Eigen/src/Core/products/SelfadjointProduct.h \
		CgMath/Eigen/src/Core/products/SelfadjointRank2Update.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixVector.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		CgMath/Eigen/src/Core/products/TriangularSolverMatrix.h \
		CgMath/Eigen/src/Core/products/TriangularSolverVector.h \
		CgMath/Eigen/src/Core/BandMatrix.h \
		CgMath/Eigen/src/Core/CoreIterators.h \
		CgMath/Eigen/src/Core/ConditionEstimator.h \
		CgMath/Eigen/src/Core/BooleanRedux.h \
		CgMath/Eigen/src/Core/Select.h \
		CgMath/Eigen/src/Core/VectorwiseOp.h \
		CgMath/Eigen/src/Core/Random.h \
		CgMath/Eigen/src/Core/Replicate.h \
		CgMath/Eigen/src/Core/Reverse.h \
		CgMath/Eigen/src/Core/ArrayWrapper.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		CgMath/Eigen/src/Core/Assign_MKL.h \
		CgMath/Eigen/src/Core/GlobalFunctions.h \
		CgMath/Eigen/src/Core/util/ReenableStupidWarnings.h \
		CgMath/Eigen/LU \
		CgMath/Eigen/src/misc/Kernel.h \
		CgMath/Eigen/src/misc/Image.h \
		CgMath/Eigen/src/LU/FullPivLU.h \
		CgMath/Eigen/src/LU/PartialPivLU.h \
		CgMath/Eigen/src/misc/lapacke.h \
		CgMath/Eigen/src/misc/lapacke_mangling.h \
		CgMath/Eigen/src/LU/PartialPivLU_LAPACKE.h \
		CgMath/Eigen/src/LU/Determinant.h \
		CgMath/Eigen/src/LU/InverseImpl.h \
		CgMath/Eigen/src/LU/arch/Inverse_SSE.h \
		CgMath/Eigen/Cholesky \
		CgMath/Eigen/Jacobi \
		CgMath/Eigen/src/Jacobi/Jacobi.h \
		CgMath/Eigen/src/Cholesky/LLT.h \
		CgMath/Eigen/src/Cholesky/LDLT.h \
		CgMath/Eigen/src/Cholesky/LLT_LAPACKE.h \
		CgMath/Eigen/QR \
		CgMath/Eigen/Householder \
		CgMath/Eigen/src/Householder/Householder.h \
		CgMath/Eigen/src/Householder/HouseholderSequence.h \
		CgMath/Eigen/src/Householder/BlockHouseholder.h \
		CgMath/Eigen/src/QR/HouseholderQR.h \
		CgMath/Eigen/src/QR/FullPivHouseholderQR.h \
		CgMath/Eigen/src/QR/ColPivHouseholderQR.h \
		CgMath/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
		CgMath/Eigen/src/QR/HouseholderQR_LAPACKE.h \
		CgMath/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		CgMath/Eigen/SVD \
		CgMath/Eigen/src/misc/RealSvd2x2.h \
		CgMath/Eigen/src/SVD/UpperBidiagonalization.h \
		CgMath/Eigen/src/SVD/SVDBase.h \
		CgMath/Eigen/src/SVD/JacobiSVD.h \
		CgMath/Eigen/src/SVD/BDCSVD.h \
		CgMath/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
		CgMath/Eigen/Geometry \
		CgMath/Eigen/src/Geometry/OrthoMethods.h \
		CgMath/Eigen/src/Geometry/EulerAngles.h \
		CgMath/Eigen/src/Geometry/Homogeneous.h \
		CgMath/Eigen/src/Geometry/RotationBase.h \
		CgMath/Eigen/src/Geometry/Rotation2D.h \
		CgMath/Eigen/src/Geometry/Quaternion.h \
		CgMath/Eigen/src/Geometry/AngleAxis.h \
		CgMath/Eigen/src/Geometry/Transform.h \
		CgMath/Eigen/src/Geometry/Translation.h \
		CgMath/Eigen/src/Geometry/Scaling.h \
		CgMath/Eigen/src/Geometry/Hyperplane.h \
		CgMath/Eigen/src/Geometry/ParametrizedLine.h \
		CgMath/Eigen/src/Geometry/AlignedBox.h \
		CgMath/Eigen/src/Geometry/Umeyama.h \
		CgMath/Eigen/src/Geometry/arch/Geometry_SSE.h \
		CgMath/Eigen/Eigenvalues \
		CgMath/Eigen/src/Eigenvalues/Tridiagonalization.h \
		CgMath/Eigen/src/Eigenvalues/RealSchur.h \
		CgMath/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		CgMath/Eigen/src/Eigenvalues/EigenSolver.h \
		CgMath/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		CgMath/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		CgMath/Eigen/src/Eigenvalues/ComplexSchur.h \
		CgMath/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		CgMath/Eigen/src/Eigenvalues/RealQZ.h \
		CgMath/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		CgMath/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		CgMath/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		CgMath/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		CgMath/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgEigenDecomposition3x3.o CgMath/CgEigenDecomposition3x3.cpp

CGQtGLRenderWidget.o: CgQtViewer/CGQtGLRenderWidget.cpp CgQtViewer/CgQtGLRenderWidget.h \
		CgBase/CgBaseRenderer.h \
		CgQtViewer/CgQtGlBufferObject.h \
		CgBase/CgBasePolyline.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h \
		CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgBase/CgBaseImage.h \
		CgBase/CgBaseSceneControl.h \
		CgQtViewer/CgTrackball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGQtGLRenderWidget.o CgQtViewer/CGQtGLRenderWidget.cpp

CgQtGui.o: CgQtViewer/CgQtGui.cpp CgQtViewer/CgQtGLRenderWidget.h \
		CgBase/CgBaseRenderer.h \
		CgQtViewer/CgQtGui.h \
		CgBase/CgObservable.h \
		CgQtViewer/CgQtMainApplication.h \
		CgBase/CgEnums.h \
		CgEvents/CgMouseEvent.h \
		CgBase/CgBaseEvent.h \
		CgEvents/CgKeyEvent.h \
		CgEvents/CgWindowResizeEvent.h \
		CgEvents/CgLoadMeshEvent.h \
		CgEvents/CgLoadHalfEdgeMeshEvent.h \
		CgEvents/CgLoadPointCloudEvent.h \
		CgEvents/CgTrackballEvent.h \
		CgEvents/CgSplatEvent.h \
		CgEvents/CgPickRayEvent.h \
		CgEvents/CgButtonClickEvent.h \
		CgSceneGraph/CgHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgSceneGraph/CgHalfEdgePrimitives.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgQtGui.o CgQtViewer/CgQtGui.cpp

CgObservable.o: CgBase/CgObservable.cpp CgBase/CgObservable.h \
		CgBase/CgObserver.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgObservable.o CgBase/CgObservable.cpp

CgMouseEvent.o: CgEvents/CgMouseEvent.cpp CgEvents/CgMouseEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgMouseEvent.o CgEvents/CgMouseEvent.cpp

CgQtMainApplication.o: CgQtViewer/CgQtMainApplication.cpp CgQtViewer/CgQtMainApplication.h \
		CgQtViewer/CgQtGui.h \
		CgBase/CgObservable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgQtMainApplication.o CgQtViewer/CgQtMainApplication.cpp

CgHalfEdgePrimitives.o: CgSceneGraph/CgHalfEdgePrimitives.cpp CgSceneGraph/CgHalfEdgePrimitives.h \
		CgBase/CgBaseHalfdgePrimitives.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgHalfEdgePrimitives.o CgSceneGraph/CgHalfEdgePrimitives.cpp

CgHalfEdgeTriangleMesh.o: CgSceneGraph/CgHalfEdgeTriangleMesh.cpp CgSceneGraph/CgHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgSceneGraph/CgHalfEdgePrimitives.h \
		CgUtils/ObjLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgHalfEdgeTriangleMesh.o CgSceneGraph/CgHalfEdgeTriangleMesh.cpp

CgPointCloud.o: CgSceneGraph/CgPointCloud.cpp CgSceneGraph/CgPointCloud.h \
		CgBase/CgBasePointCloud.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h \
		CgUtils/ObjLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgPointCloud.o CgSceneGraph/CgPointCloud.cpp

CgPolyLine.o: CgSceneGraph/CgPolyLine.cpp CgSceneGraph/CgPolyLine.h \
		CgBase/CgBasePolyline.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgPolyLine.o CgSceneGraph/CgPolyLine.cpp

CgSceneControl.o: CgSceneGraph/CgSceneControl.cpp CgSceneGraph/CgSceneControl.h \
		CgBase/CgObserver.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h \
		CgBase/CgBaseSceneControl.h \
		CgEvents/CgMouseEvent.h \
		CgEvents/CgKeyEvent.h \
		CgEvents/CgWindowResizeEvent.h \
		CgEvents/CgLoadMeshEvent.h \
		CgEvents/CgLoadHalfEdgeMeshEvent.h \
		CgEvents/CgLoadPointCloudEvent.h \
		CgEvents/CgTrackballEvent.h \
		CgEvents/CgSplatEvent.h \
		CgEvents/CgPickRayEvent.h \
		CgEvents/CgButtonClickEvent.h \
		CgBase/CgBaseRenderer.h \
		CgSceneGraph/CgPointCloud.h \
		CgBase/CgBasePointCloud.h \
		CgBase/CgBaseRenderableObject.h \
		CgSceneGraph/CgPolyLine.h \
		CgBase/CgBasePolyline.h \
		CgSceneGraph/CgTriangleMesh.h \
		CgBase/CgBaseTriangleMesh.h \
		CgSceneGraph/CgHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgSceneGraph/CgHalfEdgePrimitives.h \
		CgUtils/ObjLoader.h \
		CgMath/CgEigenDecomposition3x3.h \
		CgMath/Eigen/SVD \
		CgMath/Eigen/QR \
		CgMath/Eigen/Core \
		CgMath/Eigen/src/Core/util/DisableStupidWarnings.h \
		CgMath/Eigen/src/Core/util/Macros.h \
		CgMath/Eigen/src/Core/util/MKL_support.h \
		CgMath/Eigen/src/misc/blas.h \
		CgMath/Eigen/src/Core/util/Constants.h \
		CgMath/Eigen/src/Core/util/Meta.h \
		CgMath/Eigen/src/Core/util/ForwardDeclarations.h \
		CgMath/Eigen/src/Core/util/StaticAssert.h \
		CgMath/Eigen/src/Core/util/XprHelper.h \
		CgMath/Eigen/src/Core/util/Memory.h \
		CgMath/Eigen/src/Core/NumTraits.h \
		CgMath/Eigen/src/Core/MathFunctions.h \
		CgMath/Eigen/src/Core/GenericPacketMath.h \
		CgMath/Eigen/src/Core/MathFunctionsImpl.h \
		CgMath/Eigen/src/Core/arch/Default/ConjHelper.h \
		CgMath/Eigen/src/Core/arch/SSE/PacketMath.h \
		CgMath/Eigen/src/Core/arch/SSE/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AVX/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AVX/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AVX512/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/SSE/Complex.h \
		CgMath/Eigen/src/Core/arch/AVX/Complex.h \
		CgMath/Eigen/src/Core/arch/AVX/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/SSE/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		CgMath/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/AltiVec/Complex.h \
		CgMath/Eigen/src/Core/arch/NEON/PacketMath.h \
		CgMath/Eigen/src/Core/arch/NEON/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/NEON/Complex.h \
		CgMath/Eigen/src/Core/arch/ZVector/PacketMath.h \
		CgMath/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/ZVector/Complex.h \
		CgMath/Eigen/src/Core/arch/CUDA/Half.h \
		CgMath/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		CgMath/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		CgMath/Eigen/src/Core/arch/CUDA/PacketMath.h \
		CgMath/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		CgMath/Eigen/src/Core/arch/Default/Settings.h \
		CgMath/Eigen/src/Core/functors/TernaryFunctors.h \
		CgMath/Eigen/src/Core/functors/BinaryFunctors.h \
		CgMath/Eigen/src/Core/functors/UnaryFunctors.h \
		CgMath/Eigen/src/Core/functors/NullaryFunctors.h \
		CgMath/Eigen/src/Core/functors/StlFunctors.h \
		CgMath/Eigen/src/Core/functors/AssignmentFunctors.h \
		CgMath/Eigen/src/Core/arch/CUDA/Complex.h \
		CgMath/Eigen/src/Core/IO.h \
		CgMath/Eigen/src/Core/DenseCoeffsBase.h \
		CgMath/Eigen/src/Core/DenseBase.h \
		CgMath/Eigen/src/plugins/BlockMethods.h \
		CgMath/Eigen/src/Core/MatrixBase.h \
		CgMath/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		CgMath/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		CgMath/Eigen/src/Core/EigenBase.h \
		CgMath/Eigen/src/Core/Product.h \
		CgMath/Eigen/src/Core/CoreEvaluators.h \
		CgMath/Eigen/src/Core/AssignEvaluator.h \
		CgMath/Eigen/src/Core/Assign.h \
		CgMath/Eigen/src/Core/ArrayBase.h \
		CgMath/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		CgMath/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		CgMath/Eigen/src/Core/util/BlasUtil.h \
		CgMath/Eigen/src/Core/DenseStorage.h \
		CgMath/Eigen/src/Core/NestByValue.h \
		CgMath/Eigen/src/Core/ReturnByValue.h \
		CgMath/Eigen/src/Core/NoAlias.h \
		CgMath/Eigen/src/Core/PlainObjectBase.h \
		CgMath/Eigen/src/Core/Matrix.h \
		CgMath/Eigen/src/Core/Array.h \
		CgMath/Eigen/src/Core/CwiseTernaryOp.h \
		CgMath/Eigen/src/Core/CwiseBinaryOp.h \
		CgMath/Eigen/src/Core/CwiseUnaryOp.h \
		CgMath/Eigen/src/Core/CwiseNullaryOp.h \
		CgMath/Eigen/src/Core/CwiseUnaryView.h \
		CgMath/Eigen/src/Core/SelfCwiseBinaryOp.h \
		CgMath/Eigen/src/Core/Dot.h \
		CgMath/Eigen/src/Core/StableNorm.h \
		CgMath/Eigen/src/Core/Stride.h \
		CgMath/Eigen/src/Core/MapBase.h \
		CgMath/Eigen/src/Core/Map.h \
		CgMath/Eigen/src/Core/Ref.h \
		CgMath/Eigen/src/Core/Block.h \
		CgMath/Eigen/src/Core/VectorBlock.h \
		CgMath/Eigen/src/Core/Transpose.h \
		CgMath/Eigen/src/Core/DiagonalMatrix.h \
		CgMath/Eigen/src/Core/Diagonal.h \
		CgMath/Eigen/src/Core/DiagonalProduct.h \
		CgMath/Eigen/src/Core/Redux.h \
		CgMath/Eigen/src/Core/Visitor.h \
		CgMath/Eigen/src/Core/Fuzzy.h \
		CgMath/Eigen/src/Core/Swap.h \
		CgMath/Eigen/src/Core/CommaInitializer.h \
		CgMath/Eigen/src/Core/GeneralProduct.h \
		CgMath/Eigen/src/Core/Solve.h \
		CgMath/Eigen/src/Core/Inverse.h \
		CgMath/Eigen/src/Core/SolverBase.h \
		CgMath/Eigen/src/Core/PermutationMatrix.h \
		CgMath/Eigen/src/Core/Transpositions.h \
		CgMath/Eigen/src/Core/TriangularMatrix.h \
		CgMath/Eigen/src/Core/SelfAdjointView.h \
		CgMath/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		CgMath/Eigen/src/Core/products/Parallelizer.h \
		CgMath/Eigen/src/Core/ProductEvaluators.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixVector.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		CgMath/Eigen/src/Core/SolveTriangular.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		CgMath/Eigen/src/Core/products/SelfadjointProduct.h \
		CgMath/Eigen/src/Core/products/SelfadjointRank2Update.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixVector.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		CgMath/Eigen/src/Core/products/TriangularSolverMatrix.h \
		CgMath/Eigen/src/Core/products/TriangularSolverVector.h \
		CgMath/Eigen/src/Core/BandMatrix.h \
		CgMath/Eigen/src/Core/CoreIterators.h \
		CgMath/Eigen/src/Core/ConditionEstimator.h \
		CgMath/Eigen/src/Core/BooleanRedux.h \
		CgMath/Eigen/src/Core/Select.h \
		CgMath/Eigen/src/Core/VectorwiseOp.h \
		CgMath/Eigen/src/Core/Random.h \
		CgMath/Eigen/src/Core/Replicate.h \
		CgMath/Eigen/src/Core/Reverse.h \
		CgMath/Eigen/src/Core/ArrayWrapper.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		CgMath/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		CgMath/Eigen/src/Core/Assign_MKL.h \
		CgMath/Eigen/src/Core/GlobalFunctions.h \
		CgMath/Eigen/src/Core/util/ReenableStupidWarnings.h \
		CgMath/Eigen/Cholesky \
		CgMath/Eigen/Jacobi \
		CgMath/Eigen/src/Jacobi/Jacobi.h \
		CgMath/Eigen/src/Cholesky/LLT.h \
		CgMath/Eigen/src/Cholesky/LDLT.h \
		CgMath/Eigen/src/misc/lapacke.h \
		CgMath/Eigen/src/misc/lapacke_mangling.h \
		CgMath/Eigen/src/Cholesky/LLT_LAPACKE.h \
		CgMath/Eigen/Householder \
		CgMath/Eigen/src/Householder/Householder.h \
		CgMath/Eigen/src/Householder/HouseholderSequence.h \
		CgMath/Eigen/src/Householder/BlockHouseholder.h \
		CgMath/Eigen/src/QR/HouseholderQR.h \
		CgMath/Eigen/src/QR/FullPivHouseholderQR.h \
		CgMath/Eigen/src/QR/ColPivHouseholderQR.h \
		CgMath/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
		CgMath/Eigen/src/QR/HouseholderQR_LAPACKE.h \
		CgMath/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		CgMath/Eigen/src/misc/RealSvd2x2.h \
		CgMath/Eigen/src/SVD/UpperBidiagonalization.h \
		CgMath/Eigen/src/SVD/SVDBase.h \
		CgMath/Eigen/src/SVD/JacobiSVD.h \
		CgMath/Eigen/src/SVD/BDCSVD.h \
		CgMath/Eigen/src/SVD/JacobiSVD_LAPACKE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgSceneControl.o CgSceneGraph/CgSceneControl.cpp

CgKeyEvent.o: CgEvents/CgKeyEvent.cpp CgEvents/CgKeyEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgKeyEvent.o CgEvents/CgKeyEvent.cpp

CgButtonClickEvent.o: CgEvents/CgButtonClickEvent.cpp CgEvents/CgButtonClickEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgButtonClickEvent.o CgEvents/CgButtonClickEvent.cpp

CgQtGlBufferObject.o: CgQtViewer/CgQtGlBufferObject.cpp CgQtViewer/CgQtGlBufferObject.h \
		CgBase/CgBasePolyline.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h \
		CgBase/CgBaseHalfEdgeTriangleMesh.h \
		CgBase/CgBaseHalfdgePrimitives.h \
		CgBase/CgBaseTriangleMesh.h \
		CgBase/CgBasePointCloud.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgQtGlBufferObject.o CgQtViewer/CgQtGlBufferObject.cpp

CgTrackball.o: CgQtViewer/CgTrackball.cpp CgQtViewer/CgTrackball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgTrackball.o CgQtViewer/CgTrackball.cpp

CgWindowResizeEvent.o: CgEvents/CgWindowResizeEvent.cpp CgEvents/CgWindowResizeEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgWindowResizeEvent.o CgEvents/CgWindowResizeEvent.cpp

CgTriangleMesh.o: CgSceneGraph/CgTriangleMesh.cpp CgSceneGraph/CgTriangleMesh.h \
		CgBase/CgBaseTriangleMesh.h \
		CgBase/CgBaseRenderableObject.h \
		CgBase/CgEnums.h \
		CgUtils/ObjLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgTriangleMesh.o CgSceneGraph/CgTriangleMesh.cpp

ObjLoader.o: CgUtils/ObjLoader.cpp CgUtils/ObjLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjLoader.o CgUtils/ObjLoader.cpp

CgTrackballEvent.o: CgEvents/CgTrackballEvent.cpp CgEvents/CgTrackballEvent.h \
		CgBase/CgBaseEvent.h \
		CgBase/CgEnums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CgTrackballEvent.o CgEvents/CgTrackballEvent.cpp

moc_CgQtGLRenderWidget.o: moc_CgQtGLRenderWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CgQtGLRenderWidget.o moc_CgQtGLRenderWidget.cpp

moc_CgQtGui.o: moc_CgQtGui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CgQtGui.o moc_CgQtGui.cpp

moc_CgQtMainApplication.o: moc_CgQtMainApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CgQtMainApplication.o moc_CgQtMainApplication.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

